### ISSUE TITLE
Did anyone work with telegram gaming platform?

### ISSUE THREAD

**Issue by ahmdrz** [tucnak/telebot#73] opened 2016-11-09 10:18 UTC
Hi. I have some questions.
1. How can I get user information in game
2. How to submit score

**Comment by ahmdrz** [comment] 2016-11-09 15:25
I am working on my telegram game bot.
So if I found any way to create I will put a comment on this issue.

So I think many of methods not in this library and I will make PR for those.

**Comment by ahmdrz** [comment] 2016-11-09 15:26
My telegram game bot is 2048. See my profile .
I have 2048 html5 game in my repositories.

**Comment by tucnak** [comment] 2016-11-09 21:31
Virtually duplicate of #67. Please keep all of the discussion on gaming platform there instead.

**Closed by tucnak** 2016-11-09 21:31 UTC
Labels: duplicate
