### ISSUE TITLE
Add payments

### ISSUE THREAD

**Issue by CssHammer** [tucnak/telebot#186] opened 2019-01-23 21:34 UTC
When payments will be available?

**Comment by michaellee8** [comment] 2019-02-13 02:51
@tucnak Do you have any plan to integrate it?

**Comment by tucnak** [comment] 2019-02-13 11:07
Payments are already partially implemented in master, but it's not a complete implementation, so I didn't announce it. I'm currently maybe too busy to implement the remaining bits, but will do so eventually.

**Comment by michaellee8** [comment] 2019-02-17 14:07
It is great, I can see that from godoc. hope that it will come eventually

**Comment by michaellee8** [comment] 2019-02-19 12:41
@tucnak I actually have a bot that may uses Telegram Payment in active development. If I am in that stage of development before you have done that, may I contribute it?

**Comment by tucnak** [comment] 2019-02-19 21:32
Yes please!

**Comment by stek29** [comment] 2019-12-26 10:08
duplicate of #101

**Closed as completed by stek29** 2019-12-26 10:08 UTC
